const viewProps = Object.freeze({
    YouthDetails: {
        name: "Youth Details", // Update the name as needed
        columnHeads: [
            "ID",
            "FORM NUMBER",
            "FULL NAME",
            "DATE OF BIRTH",
            "AGE",
            "GENDER",
            "PERMANENT ADDRESS",
            "CURRENT ADDRESS",
            "MOBILE NUMBER",
            "WHATSAPP NUMBER",
            "EMAIL",
            "HIGHEST EDUCATIONAL QUALIFICATION",
            "CURRENT OCCUPATION",
            "PROFESSIONAL DETAILS",
            "CURRENT COURSE",
            "BAPTISM (sacraments)",
            "CONFIRMATION (sacraments)",
            "HOLY COMMUNION (sacraments)",
            "PENDING SACRAMENTS",
            "HAS ORGANISATION GROUP",
            "ORGANISATION GROUP",
            "HAS PARISH ACTIVITY",
            "PARISH ACTIVITY",
            "IS OUTSIDE PARISH",
            "IS STUDENT",
            "COUNTRY CITY",
            "PARISH CONTACT",
            "RESIDENTIAL ADDRESS",
            "IS ATTENDING SUNDAY MASS REGULARLY",
            "SUNDAY MASS LOCATION",
            "HOUSE NAME",
            "PARENTS NAME",
            "PARENTS NUMBER",
            "UNIT",
            "SPECIALS",
            "HEALTH ISSUES",
        ],
        relevants: [
            "prefixedId",
            "formNumber",
            "fullName",
            "dateOfBirth",
            "age",
            "gender",
            "permanentAddress",
            "currentAddress",
            "mobileNumber",
            "whatsappNumber",
            "email",
            "educationalQualification",
            "currentOccupation",
            "professionalDetails",
            "currentCourse",
            "sacraments.baptism",
            "sacraments.confirmation",
            "sacraments.holyCommunion",
            "pendingSacraments",
            "hasOrganisationGroup",
            "organisationGroup",
            "hasParishActivity",
            "parishActivity",
            "isOutsideParish",
            "isStudent",
            "countryCity",
            "parishContact",
            "residentialAddress",
            "isAttendingSundayMass",
            "sundayMassLocation",
            "houseName",
            "parentsName",
            "parentsNumber",
            "unit",
            "specials",
            "healthIssues",
        ],
    },
});

export default viewProps;
